#!/bin/bash
docker build --no-cache -f src/main/docker/Dockerfile.jvm -t registry.gilmariosoftware.com.br/chat-integracao:latest .
docker tag registry.gilmariosoftware.com.br/chat-integracao:latest registry.gilmariosoftware.com.br/chat-integracao:2.1.0
