#!/bin/bash
#docker build -f src/main/docker/Dockerfile.jvm -t chat-integracao:$1 .

#docker build -f src/main/docker/Dockerfile.jvm -t chat-integracao:latest .

docker build -f src/main/docker/Dockerfile.jvm -t registry.gilmariosoftware.com.br/chat-integracao:2.0.0 .

docker build -f src/main/docker/Dockerfile.jvm -t registry.gilmariosoftware.com.br/chat-integracao:latest .