#! /bin/bash
APP_NAME=chati

docker rm -f $APP_NAME

docker run -d \
    --name $APP_NAME -d \
    --network local \
    -p 8080:8080 \
    -e POCKETBASE_URL=http://pocketbase:8080 \
    -e POCKETBASE_USUARIO=chatintegracao@email.com \
    -e POCKETBASE_SENHA=kpslow@0909 \
    -e POCKETBASE_COLLECTION=chati \
    registry.gilmariosoftware.com.br/chat-integracao:latest